export {default as Hero } from './Hero.jsx'
export {default as Sales } from './Sales.jsx'
export {default as FlexContent } from './FlexContent.jsx'
export {default as Stories } from './Stories.jsx'
export {default as Footer } from './Footer.jsx'
export {default as Navbar } from './Navbar.jsx'
export {default as Cart } from './Cart.jsx'
export {default as NewCart } from './NewCart.jsx'
export {default as Product } from './Product.jsx'
export {default as ClientOrders } from './ClientOrders.jsx'
export {default as SignUp } from '../Registration/SignUp.jsx'
export {default as Login } from '../Registration/Login.jsx'
export {default as DefaultLayout } from '../Layouts/DefaultLayout.jsx'
export {default as GuestLayout } from '../Layouts/GuestLayout.jsx'
export {default as Profile} from '../Views/Profile.jsx'
export {default as NotFound} from '../Views/NotFound.jsx'